# @baseURL = https://ecoapp-backend-1043095433635.us-central1.run.app
@baseURL = http://localhost:3333 
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseURL}}/accounts
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "caiopaulista@ecoeletrica.com.br",
  "email": "caio2@ecoeletrica.com.br",
  "cpf": "10101010110",
  "type": "Orçamentista",
  "baseId": "dbe82710-e5e8-449a-ba49-471b356f808d",
  "contractId": "a100663c-5a6d-4198-ad7b-1062afa0c4f4",
  "password": "testeteste"
}

###

# @name authenticate
POST {{baseURL}}/sessions
Content-Type: application/json

{
    "email": "rodrigo@ecoeletrica.com.br",
    "password": "ECO@2012" 
}

###

# @name create_material
POST {{baseURL}}/materials
Content-Type: application/json
Authorization: Bearer {{authToken}}

[
    {
        "code": 11111113,
        "description": "item poste 123",
        "type": "FERRAGEM",
        "unit": "CDA"
    },
    {
        "code": 11111112,
        "description": "item poste 123",
        "type": "FERRAGEM",
        "unit": "CDA"
    }
]

###

# @name fetch_materials
GET {{baseURL}}/materials
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name get_user_by_id
GET {{baseURL}}/accounts/612d36fb-3cde-42de-bae0-ef8e547a9807
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name edit_account
PUT {{baseURL}}/accounts/627a842b-eeee-42f2-b8aa-9a9fbdee0b83
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "type": "Administrator"
}

###

# @name delete_user_by_id
DELETE  {{baseURL}}/accounts/2d8c64e4-0ae3-448e-8fa4-eb4edaaaf963
Content-Type: application/json
Authorization: Bearer {{authToken}}


###

# @name fetch_account
GET {{baseURL}}/accounts
# ?baseId=dbe82710-e5e8-449a-ba49-471b356f808d
Content-Type: application/json
Authorization: Bearer {{authToken}}


###

# @name register_contract
POST {{baseURL}}/contracts
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "contractName": "Oeste Pernambuco"
}


###

# @name fetch_contracts
GET {{baseURL}}/contracts?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}


###

# @name register_base
POST {{baseURL}}/bases
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "baseName": "Petrolina",
    "contractId": "a100663c-5a6d-4198-ad7b-1062afa0c4f4"
}


###

# @name fetch_bases
GET {{baseURL}}/bases?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}


###

# @name identifier_attribution
POST {{baseURL}}/physical-documents
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "project_number": "B-12345678",
    "identifier": 1
}


###

# @name fetch_physical_documents
GET {{baseURL}}/physical-documents
?unitized=true
Content-Type: application/json
Authorization: Bearer {{authToken}}



###

# @name uniteze_physical_documents
PUT {{baseURL}}/physical-documents/fc13dc69-7493-4644-9667-576cfaf85735
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "unitized": true
}


###

# @name delete_physical_document
DELETE  {{baseURL}}/physical-documents/88b6a558-046d-47bf-be45-11fccec6d328
Content-Type: application/json
Authorization: Bearer {{authToken}}


###

# @name transfer_material
POST  {{baseURL}}/movimentation
Content-Type: application/json
Authorization: Bearer {{authToken}}

[
    {
        "materialId": "18c41419-c993-4b62-8672-ded49ee06d3d",
        "projectId": "44e9fa57-e4fd-4c41-a7d6-c456cc75ea98",
        "observation": "cia CIA cia Cia cia",
        "value": 5
    },
    {
        "materialId": "7a7b5a91-e91a-4340-8a5f-5e1acdf502f8",
        "projectId": "44e9fa57-e4fd-4c41-a7d6-c456cc75ea98",
        "observation": "",
        "value": 2
    }
]


###

# @name register_project
POST  {{baseURL}}/projects
Content-Type: application/json
Authorization: Bearer {{authToken}}

[
    {
        "project_number": "B-teste3",
        "description": "MP-CCOL-POV. OLHOS D'AGUA-RURAL",
        "type": "obra",
        "baseId": "468c0cdb-b89f-425c-8e8f-0551f5db94b7",
        "city": "MORRO DO CHAPEU"
    },
    {
        "project_number": "B-teste2",
        "description": "MP-CCOL-POV. OLHOS D'AGUA-RURAL",
        "type": "obra",
        "baseId": "468c0cdb-b89f-425c-8e8f-0551f5db94b7",
        "city": "MORRO DO CHAPEU"
    }
]

###

# @name transfer_movimentation_between_projects
POST  {{baseURL}}/transfer-movimentation
Content-Type: application/json
Authorization: Bearer {{authToken}}

[
    {
        "materialId": "88b6a558-046d-47bf-be45-11fccec6d328",
        "projectIdOut": "88b6a558-046d-47bf-be45-11fccec6d328",
        "projectIdIn": "30d2f9c4-decc-418a-bc5d-0fb16db7af57",
        "observation": "Num sei das quantas",
        "baseId": "88b6a558-046d-47bf-be45-11fccec6d328",
        "value": 5
    }
]

###

# @name fetch_movimentations
GET {{baseURL}}/movimentations
# ?project_number=B-12345678
# &material_code=110014
Content-Type: application/json
Authorization: Bearer {{authToken}}


###

# @name fetch_movimentations_budgets
GET {{baseURL}}/movimentations-budgets
?project_number=B-12345678
&physicalDocument=true
&projectIn=B-1234567
Content-Type: application/json
Authorization: Bearer {{authToken}}


###

# @name fetch_budgets
GET {{baseURL}}/budgets
?project_number=B-22345678
Content-Type: application/json
Authorization: Bearer {{authToken}}


###

# @name get_project_by_project_number
GET {{baseURL}}/projects
?project_number=B-teste2
Content-Type: application/json
Authorization: Bearer {{authToken}}



###

# @name register_budget
POST  {{baseURL}}/budgets
Content-Type: application/json
Authorization: Bearer {{authToken}}

[
    {
        "materialId": "b21ba24a-b752-4415-9fc4-702ec851c5cf",
        "projectId": "44e9fa57-e4fd-4c41-a7d6-c456cc75ea98",
        "value": 5,
        "createdAt": "2025-10-10T18:49:36.121Z"
    },
    {
        "materialId": "7a7b5a91-e91a-4340-8a5f-5e1acdf502f8",
        "projectId": "44e9fa57-e4fd-4c41-a7d6-c456cc75ea98",
        "value": 2
    }
]


###

# @name edit_budget
PUT  {{baseURL}}/budgets/30d2f9c4-decc-418a-bc5d-0fb16db7af57
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "updatedBudgets": [{
        "budgetId": "245dedfe-2c7c-4e6e-b10f-a6003a53d601",
        "value": 250
    }],
    "newBudgets": [{
        "materialId": "386dafeb-d232-4857-ab91-746643045bf3",
        "value": 2
    }]
}

###

# @name fetch_budgets_only_projects
POST {{baseURL}}/budgets-only-projects
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "project_numbers": ["B-12345678", "B-22345678"]
}

###

# @name fetch_existing_budgets
POST {{baseURL}}/fetch-existing-budgets
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "projectIds": [
        "62d32c48-9b11-4655-b9f0-135d9900fefd",
"9680ae3c-81f1-4964-b0c2-af715054a85a",
"58da7ce4-47c1-434b-8270-942d8c5ce12e",
"e1c54d5d-3c2c-4adc-ae32-52ef3fe27ae9",
"fc682a74-11d2-4f1f-9e00-6e0376d3f012",
"2325e471-c621-481e-8eb8-d1493b8f1e74",
"1b77a131-f482-43b6-b20b-34860c5f2a45",
"0dbd7577-c2c1-4cd8-a2a4-a8f96cdca497",
"02df6fc9-da31-426b-97ec-791a1866ef7e",
"4293c618-76d7-4f7d-9693-93a0bc330fa0",
"806e8549-7dcf-4a51-bbaf-bcb647d88b59",
"b4d11c02-1156-437b-8564-a7cf892df466",
"184009a1-9dc7-4788-a64f-117ecb4fbfd3",
"636b0c98-9134-45e7-81d5-d526d6441ce2",
"0cf5fdb3-5f0a-4f32-959e-c4ec810f1b17",
"9263427b-9e17-4244-b15a-a62ccee6ba8f",
"9de4abbb-7718-4b61-9f37-bc6dc68ac73d",
"c6814b8b-397c-42a5-b297-0374a7c9c8a7",
"aa9caef2-eee8-4d93-a2a8-88e0c6b63778",
"ad5897a9-c696-4143-ad03-daead96463ec",
"4ca67c27-fec1-42dd-9f02-d045c21aa003",
"484189f4-1d02-4a7d-8671-13abf5f61717",
"dc10d2ee-8174-4a28-8349-c7fd768b0948",
"60aa46cb-21a8-4642-9950-287b1fa3dd5b",
"956d0135-292e-4383-b22f-b14fcc9c2f66",
"79ece9db-310b-4c9b-81c6-69a5dfefe650",
"3501fede-c595-4096-8c87-aeb51cd2689d",
"9881d91f-cfde-4171-b49f-098537e8e362",
"61acc453-05d0-4d18-8497-eee84fb48dfa",
"28f8e184-d03e-4b64-8bf2-a38553248283",
"6d62e599-4daf-489b-8ec3-ebb7099bb602",
"118da4dc-954f-4384-b306-a97f470d8250",
"3c874169-5f94-461c-a73d-11497b4120cf",
"decdb24d-e966-44b5-ac43-369dc69e535a",
"09b54184-34c9-44e8-8839-7953f5972520",
"62cd4253-eb0a-4619-9263-5c22d8d926e7",
"9e30feb0-64a4-4ee2-88ae-96f848db3034",
"5c5f60fc-ebc1-4c2d-b971-de957bd9988d",
"0c6f72e7-7ccc-4faf-9240-8c9c2b8f5c60",
"ed571093-2a84-42f4-a40e-3bd188caa024",
"d463cfd3-9437-4900-8bbd-7e5f4fdad369",
"95513dff-6d2f-4fec-a6b2-47e982756a30",
"a65cd58d-e677-4973-8e3c-c891b7c4c31d",
"2c2faffc-6686-4863-9d11-9248aae620a8",
"1726b0f8-cfc4-4519-b7fb-e65deacb4f5a",
"aa1eab8d-5a1d-4710-88bd-f016781fd6e3",
"c9096e52-aa08-404f-92ae-37f058379360",
"72b728b0-7916-45aa-a731-49fc4db64cda",
"b550cc60-8266-4822-892a-2d7b816dc1e3",
"c2d7b595-1a4c-4b14-9ea4-460c443593ce",
"deab4b2c-5236-44f9-97f7-c28001943c42",
"6a26fbee-e2f2-4e41-a66b-2e5d2af0f800",
"61e6356f-cbef-40a9-bb8b-158bfe29046e",
"2faa8714-7928-4d48-b3dd-4fea352ad639",
"cff08f4d-09c5-4524-9cae-8c71cd43cdff",
"cc11858f-547b-4291-b9c2-586d2de4ec34",
"fb487710-43ab-4617-9b25-6553739146b9",
"c9feba7c-82d0-439e-b1b4-bc9bd4f6616b",
"2348b248-cc6c-4256-8a68-8c6f52272839",
"653a4dea-99eb-494e-b94c-da57b8bdeb31",
"5baf0dfa-9952-451f-a6cc-602a2ecb1944",
"c2e3752a-30da-441a-9af7-1aa97b87314e",
"2bcfb072-21c9-4e6c-b30b-d9bc2f4121d6",
"c6d75b1d-a205-4009-b074-d55d3058d9f6",
"4b7ea0c9-6333-4b91-bfae-38c7bb4e8e36",
"1c1c5bc8-c548-47d6-a545-96f9bb7e768b",
"aae6ea89-d291-464e-b145-37df66455d19",
"54781cec-c885-4a61-9c83-3930e12fec82",
"b31f1071-939c-4824-b092-c38703280942",
"569a4fda-a347-4d2d-8440-1d11b5a504fe",
"acf7ca2b-a4eb-4035-8c15-fb14865b08bc",
"e92b18cc-0605-4f78-bf43-bb2ba64614c8",
"45bcd12d-5219-44a0-87c3-fc53e9b90da0",
"01cc86ba-45a2-471d-9f52-ed107867e460",
"16232130-dd3a-4aaf-9c08-609e4d1e3cbf",
"44cd0bda-cab3-43b0-aa8c-e1fad7913895",
"fa85f1d6-19c9-4f84-a4b6-65e27a68dba3",
"c5bf8086-e2f0-4ca7-ba05-81a2705a8a1d",
"7ea98b94-615b-4b62-8f91-f8bf59151c15",
"25f1ad33-25dc-4549-907c-040e981f7df5",
"da49c032-64e3-4d7d-8ec9-2d9678d6a963",
"d524076e-4183-4498-8b95-e8602b7c9ef4",
"fd9cf390-b5e1-43fc-9752-9fcf34b78993",
"ad59fd75-f161-4491-84a1-52f086256d6e",
"080ad06a-5e0f-4d9c-a445-1a7d81c725d0",
"7b9c3cd7-dad2-46c2-8c5e-97d7642d3394",
"0e2fbdad-3c21-40cd-bd9d-eda411bbec8d",
"54376096-41f8-4686-b5fb-0285933f9a6f",
"1bc833d9-9b78-471f-90f3-a010e640d5f2"
    ]
}